document.addEventListener("DOMContentLoaded", () => {
  const rawArchiveData = [
    {
      id: "other-electronics",
      theme: "cyan",
      code: "EL",
      label: "System / 01",
      title: "Other electronics",
      summary: "Repair bench systems, captured media, and utility hardware branches.",
      rootUrl: "html/project1/index.html",
      projects: [
        {
          id: "oe-01",
          title: "Repair bench",
          tagline: "Diagnostics, teardown logs, and recovered hardware notes.",
          enterUrl: "html/project1/index.html",
          versions: [
            {
              id: "oe-01-v10",
              label: "V1.0",
              state: "Bench start",
              summary: "Base repair structure for logging fixes, parts, and opening notes.",
              tags: ["Diagnostics", "Bench", "Logs"],
              runUrl: "",
              downloadUrl: "",
            },
            {
              id: "oe-01-v12",
              label: "V1.2",
              state: "Capture pass",
              summary: "Adds clearer image tracking and first-pass component references.",
              tags: ["Capture", "Photos", "Repair"],
              runUrl: "",
              downloadUrl: "",
            },
            {
              id: "oe-01-v20",
              label: "V2.0",
              state: "Archive sync",
              summary: "A cleaner archive-ready structure for bigger repair sessions.",
              tags: ["Archive", "Sync", "Inventory"],
              runUrl: "",
              downloadUrl: "",
            },
          ],
        },
        {
          id: "oe-02",
          title: "Device library",
          tagline: "Cataloging utility gear, references, and recurring parts packs.",
          enterUrl: "html/project1/index.html",
          versions: [
            {
              id: "oe-02-v08",
              label: "V0.8",
              state: "Prototype",
              summary: "Initial device shelf for simple references and part groupings.",
              tags: ["Library", "Parts", "Refs"],
              runUrl: "",
              downloadUrl: "",
            },
            {
              id: "oe-02-v10",
              label: "V1.0",
              state: "Stable base",
              summary: "First stable catalog format with better naming and grouping.",
              tags: ["Catalog", "Stable", "Naming"],
              runUrl: "",
              downloadUrl: "",
            },
            {
              id: "oe-02-v13",
              label: "V1.3",
              state: "Expanded",
              summary: "Opens space for more devices, media, and quick lookup notes.",
              tags: ["Expanded", "Lookup", "Media"],
              runUrl: "",
              downloadUrl: "",
            },
          ],
        },
        {
          id: "oe-03",
          title: "Media capture lab",
          tagline: "Photos, clips, and visual references around physical builds.",
          enterUrl: "html/project1/index.html",
          versions: [
            {
              id: "oe-03-v09",
              label: "V0.9",
              state: "Draft rig",
              summary: "Draft visual workflow for documenting repairs and gear layout.",
              tags: ["Media", "Draft", "Capture"],
              runUrl: "",
              downloadUrl: "",
            },
            {
              id: "oe-03-v11",
              label: "V1.1",
              state: "Refined",
